### ISSUE TITLE
[Kerberos]ConcurrentModificationException kafka010.CachedKafkaConsumer

### ISSUE THREAD

**Issue by raindaywhu** [OCSP/OCSP_mainline#164]
在spark1.6 中，使用spark-kafka-0-10-connector_2.10-1.0.1.jar 来基于kafka010版本api创建spark stream时，stream 运行过程中出现以下异常：
`17/07/31 15:23:00 WARN TaskSetManager: Lost task 4.0 in stage 18.0 (TID 81, ks77.aicloud.local): java.lang.IllegalStateException: This consumer has already been closed.
        at org.apache.kafka.clients.consumer.KafkaConsumer.ensureNotClosed(KafkaConsumer.java:1543)
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1554)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:967)
        at org.apache.spark.streaming.kafka010.CachedKafkaConsumer.poll(CachedKafkaConsumer.scala:98)
        at org.apache.spark.streaming.kafka010.CachedKafkaConsumer.get(CachedKafkaConsumer.scala:72)
        at org.apache.spark.streaming.kafka010.KafkaRDD$KafkaRDDIterator.next(KafkaRDD.scala:227)
        at org.apache.spark.streaming.kafka010.KafkaRDD$KafkaRDDIterator.next(KafkaRDD.scala:193)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:148)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

在测试中发现如果--executor-cores 为1 即 一个executor 同时只运行一个task，该问题不会出现。

在官方中发现有类似的issue
https://issues.apache.org/jira/browse/SPARK-19185
即在使用Spark-Streaming-Kafka-010 时，kafka010的consumer api 不支持多线程，如果多线程并发访问，kafkaConsumer会抛出异常。
![image](https://user-images.githubusercontent.com/11971136/28772200-064d65ca-7618-11e7-88d7-40cd08d6e2eb.png)

该问题目前官方没有修复，根据给出的建议：
Failing that, KafkaRDD's constructor takes a boolean parameter indicating whether to use the consumer cache. You can straightforwardly modify DirectKafkaInputDStream.compute to pass false. This will require rebuilding only the kafka consumer jar, not redeploying all of spark. This will be a performance hit, especially if you're using SSL, but is better than nothing.

修改spark-kafka-0-10-connector中创建KafkaRDD的语句，使得使用参数consumer的参数为false，即在一个jvm上 是否创建多个consumer。
该参数的说明如下：
![image](https://user-images.githubusercontent.com/11971136/28772331-78b06ec8-7618-11e7-9bf6-4aff1c91f89e.png)

修改该参数为fasle后，更新spark-kafka-0-10-connector 问题解决。 

注意：
**1 上述建议中指出可能对性能有影响，需要后续测试。
2 根据该issue， 在spark2.0 以上版本 使用spak-streaming-kafka010也会遇到该问题。**

**Comment by raindaywhu** [comment]
根据https://issues.apache.org/jira/browse/SPARK-19185中的提交，得知在spark2.2.0以上版本，即spark-streaming-kafka-0-10_2.11-2.2.0.jar中修复了该问题，可以通过配置：
sparkConf.set("spark.streaming.kafka.consumer.cache.enabled", "false")来关闭 kafka consumer cache功能，这样每个task都会创建一个kafka consumer，而不是executor中只创建一个。
注意只有在spark2.2.0以上才支持该配置。
<groupId>org.apache.spark</groupId>
     <artifactId>spark-streaming-kafka-0-10_2.11</artifactId>
<version>2.2.0</version>
