### ISSUE TITLE
优化标签的参数配置

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#73]
现在的**标签参数**中必须包含props和labelItems，而且不能忽略大小写，这样导致如果标签参数什么都不填或者填错漏填属性就会导致打标签失败，这里需要做更强的容错处理，以及更友好的用户交互
```
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3110)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
	at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:19)
	at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:44)
	at com.asiainfo.ocdp.stream.tools.Json4sUtils$.jsonStr2ArrMap(Json4sUtils.scala:135)
	at com.asiainfo.ocdp.stream.service.DataInterfaceServer$$anonfun$getLabelsByIFId$2.apply(DataInterfaceServer.scala:98)
	at com.asiainfo.ocdp.stream.service.DataInterfaceServer$$anonfun$getLabelsByIFId$2.apply(DataInterfaceServer.scala:83)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.asiainfo.ocdp.stream.service.DataInterfaceServer.getLabelsByIFId(DataInterfaceServer.scala:83)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask.<init>(DataInterfaceTask.scala:37)
	at com.asiainfo.ocdp.stream.manager.StreamTaskFactory$.getStreamTask(StreamTaskFactory.scala:15)
	at com.asiainfo.ocdp.stream.manager.StreamApp$.main(StreamApp.scala:51)
	at com.asiainfo.ocdp.stream.manager.StreamApp.main(StreamApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by DoraemonXX** [comment]
在UI交互方式没有优化的情况下，先增强后端的容错能力
目前标准的标签参数的格式为：
```json
{
    "props": [
        {
            "pname": "user_info_cols",
            "pvalue": "acyc_id"
        }
    ],
    "labelItems": [
        {
            "pname": "phone_no",
            "pvalue": "product_no"
        }
    ]
}
```
后端需要做如下的容错处理
1. 标签参数可以为空

2. 校验用户输入是否符合json格式，如不符合给出报错信息。如果输入的是下面的内容，程序应该报错退出，并可以在日志中找到“json格式错误”的信息。
```json
{
    "props": 
        {
            "pname": "user_info_cols",
            "pvalue": "acyc_id"
        }
    ],
    "labelItems": [
        {
            "pname": "phone_no",
            "pvalue": "product_no"
        }
    ]
}
```
3. json中可以有任意元素，但是后台只提取props和labelItems，如有其他属性在日志中给出警告信息。如果用户输入下面的内容，那么abc这个属性是多余的，后台程序并不会获取，这种情况日志中应该有告警提示信息，“ abc属性无效”，程序继续执行。
```json
{
    "props": [
        {
            "pname": "user_info_cols",
            "pvalue": "acyc_id"
        }
    ],
    "labelItems": [
        {
            "pname": "phone_no",
            "pvalue": "product_no"
        }
    ],
    "abc": [
        {
            "pname": "phone_no",
            "pvalue": "product_no"
        }
    ]
}
```
4. 如果找不到props或者labelItems要在日志中给出警告信息。如果是下面这种情况，日志中应该给出告警提示信息“ abc属性无效”和“没有找到props和labelItems属性”，程序继续执行。
```json
{
    "abc": [
        {
            "pname": "phone_no",
            "pvalue": "product_no"
        }
    ]
}
```
5. props或者labelItems允许有任意一个或者都存在。如果是下面这种情况，日志中应该给出告警“没有找到labelItems属性”，程序继续执行。
```json
{
    "props": [
        {
            "pname": "user_info_cols",
            "pvalue": "acyc_id"
        }
    ]
}
```

**Comment by DoraemonXX** [comment]
Fixed
