### ISSUE TITLE
Event中的过滤条件为空会导致异常

### ISSUE THREAD

**Issue by DoraemonXX** [OCSP/OCSP_mainline#80]
异常为：
```
2017-03-08 14:52:06,640 ERROR [JobScheduler] JobScheduler:95 - Error running job streaming job 1488955920000 ms.0
java.util.concurrent.ExecutionException: scala.MatchError: Failure(java.lang.RuntimeException: [1.1] failure: end of input


^) (of class scala.util.Failure)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$makeEvents$2.apply(DataInterfaceTask.scala:370)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$makeEvents$2.apply(DataInterfaceTask.scala:369)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask.makeEvents(DataInterfaceTask.scala:369)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$process$1.apply(DataInterfaceTask.scala:160)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$process$1.apply(DataInterfaceTask.scala:119)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:661)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:661)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:426)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:49)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:49)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:49)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:227)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:227)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:227)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:226)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: scala.MatchError: Failure(java.lang.RuntimeException: [1.1] failure: end of input


^) (of class scala.util.Failure)
	at com.asiainfo.ocdp.stream.event.Event.buildEvent(Event.scala:41)
	at com.asiainfo.ocdp.stream.datasource.BuildEvent.call(DataInterfaceTask.scala:381)
	at com.asiainfo.ocdp.stream.datasource.BuildEvent.call(DataInterfaceTask.scala:379)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
java.util.concurrent.ExecutionException: scala.MatchError: Failure(java.lang.RuntimeException: [1.1] failure: end of input


^) (of class scala.util.Failure)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$makeEvents$2.apply(DataInterfaceTask.scala:370)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$makeEvents$2.apply(DataInterfaceTask.scala:369)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask.makeEvents(DataInterfaceTask.scala:369)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$process$1.apply(DataInterfaceTask.scala:160)
	at com.asiainfo.ocdp.stream.datasource.DataInterfaceTask$$anonfun$process$1.apply(DataInterfaceTask.scala:119)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:661)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:661)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:426)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:49)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:49)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:49)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:227)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:227)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:227)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:226)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: scala.MatchError: Failure(java.lang.RuntimeException: [1.1] failure: end of input


^) (of class scala.util.Failure)
	at com.asiainfo.ocdp.stream.event.Event.buildEvent(Event.scala:41)
	at com.asiainfo.ocdp.stream.datasource.BuildEvent.call(DataInterfaceTask.scala:381)
	at com.asiainfo.ocdp.stream.datasource.BuildEvent.call(DataInterfaceTask.scala:379)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

**Comment by DoraemonXX** [comment]
Fixed
