### ISSUE TITLE
Restart 操作可能会失败

### ISSUE THREAD

**Issue by raindaywhu** [OCSP/OCSP_mainline#83]
对正在执行的Stream进行重启操作时，可能会失败，会有多种提示信息如下：
错误信息1
15:13:20.616 [Task build timer] ERROR c.a.o.s.manager.MainFrameManager - Error start new app 
akka.actor.InvalidActorNameException: actor name [task_1] is not unique!
        at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130) ~[akka-actor_2.10-2.3.3.jar:na]
        at akka.actor.dungeon.Children$class.reserveChild(Children.scala:77) ~[akka-actor_2.10-2.3.3.jar:na]
        at akka.actor.ActorCell.reserveChild(ActorCell.scala:369) ~[akka-actor_2.10-2.3.3.jar:na]
        at akka.actor.dungeon.Children$class.makeChild(Children.scala:202) ~[akka-actor_2.10-2.3.3.jar:na]
        at akka.actor.dungeon.Children$class.attachChild(Children.scala:42) ~[akka-actor_2.10-2.3.3.jar:na]
        at akka.actor.ActorCell.attachChild(ActorCell.scala:369) ~[akka-actor_2.10-2.3.3.jar:na]
        at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:552) ~[akka-actor_2.10-2.3.3.jar:na]
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$$anonfun$buildTask$1.apply(MainFrameManager.scala:93) ~[core-2.0.1.jar:na]
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$$anonfun$buildTask$1.apply(MainFrameManager.scala:80) ~[core-2.0.1.jar:na]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) ~[scala-library-2.10.4.jar:na]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) ~[scala-library-2.10.4.jar:na]
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$.buildTask(MainFrameManager.scala:80) ~[core-2.0.1.jar:na]
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$$anon$1.run(MainFrameManager.scala:56) ~[core-2.0.1.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_77]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_77]

错误信息2
2017-03-16 14:43:38,716 INFO [dispatcher-event-loop-2] BlockManagerMasterEndpoint:58 - Registering block manager ochadoop19.jcloud.local:36031 with 511.1 MB RAM, BlockManagerId(2, ochadoop19.jcloud.local, 36031)
2017-03-16 14:43:38,839 INFO [dispatcher-event-loop-11] YarnClientSchedulerBackend:58 - Registered executor NettyRpcEndpointRef(null) (ochadoop20.jcloud.local:58773) with ID 6
@
?Listener
2017-03-16 14:31:35,399 INFO [Task stop timer] SparkUI:58 - Stopped Spark web UI at http://192.168.0.33:4042
Exception in thread "Task build timer" java.lang.NoClassDefFoundError: com/asiainfo/ocdp/stream/manager/MainFrameManager$$anon$1$$anonfun$run$1
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$$anon$1.run(MainFrameManager.scala:59)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: com.asiainfo.ocdp.stream.manager.MainFrameManager$$anon$1$$anonfun$run$1
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
2017-03-16 14:31:35,800 ERROR [heartbeat-receiver-event-loop-thread] LiveListenerBus:74 - SparkListenerBus has already stopped! Dropping event SparkListenerExecutorMetricsUpdate(7,WrappedArray())
2017-03-16 14:31:37,099 ERROR [heartbeat-receiver-event-loop-thread] LiveListenerBus:74 - SparkListenerBus has already stopped! Dropping event SparkListenerExecutorMetricsUpdate(6,WrappedArray())

**Comment by raindaywhu** [comment]
见官方文档
Since stopping an actor is asynchronous, you cannot immediately reuse the name of the child you just stopped; this will result in an InvalidActorNameException. Instead, watch the terminating actor and create its replacement in response to the Terminated message which will eventually arrive.
http://doc.akka.io/docs/akka/2.1.0/scala/actors.html

另外移除了SparkListener， 注册onApplicationEnd操作已经在主函数中执行。
