### ISSUE TITLE
[bug]无法启动OCSP MainFrame

### ISSUE THREAD

**Issue by biggeng** [OCSP/OCSP_mainline#89]
描述：安装OCDP_Stream_2.1.0-beta包后，按照指定步骤进行环境配置，执行“stream start”命令启动OCSP，报错，查看后台log如下：
2017-03-27 21:56:16,082 INFO [main] MainFrameManager:36 - = = = = = = = = = = = = = = = = MainFrameManager Server start at 2017-03-27 21:56:16= = = = = = = = = = = = = = = =
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  finish initMainFrameConf
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.asiainfo.ocdp.stream.manager.MainFrameManager.main(MainFrameManager.scala)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'appID' in 'field list'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
        at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1446)
        at com.asiainfo.ocdp.stream.common.JDBCUtil$.query(JDBCUtil.scala:45)
        at com.asiainfo.ocdp.stream.service.TaskServer.getAllTaskInfos(TaskServer.scala:117)
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$.<init>(MainFrameManager.scala:43)
        at com.asiainfo.ocdp.stream.manager.MainFrameManager$.<clinit>(MainFrameManager.scala)
        ... 1 more

**Comment by DoraemonXX** [comment]
@raindaywhu 请同步一下两个sql脚本，create_tables.sql脚本有遗漏，多谢

**Comment by DoraemonXX** [comment]
@raindaywhu STREAM_EXCEPTION这个表的定义在create_tables.sql中也遗漏了

**Comment by raindaywhu** [comment]
fixed
